services:
  application:
    build:
      context: ./application
      dockerfile: Dockerfile
    image: project_febe_application
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BE_URL=http://be:5000
    networks:
      - app-network
    depends_on:
      - be
    mem_limit: 1024M
    cpus: 1

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    image: project_febe_be
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FRONTEND_URL=http://fe:3001
    networks:
      - app-network
    mem_limit: 1024M
    cpus: 1

networks:
  app-network:
    driver: bridge
