services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: project_febe_base

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    image: project_febe_fe
    depends_on:
      - base
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    image: project_febe_be
    depends_on:
      - base
    ports:
      - "5000:5000"
    environment:
      - PDF_RENDERER_URL=http://fe:3001
