services:
  application:
    build:
      context: ./application
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BE_URL=http://localhost:5000
    networks:
      - app-network
    depends_on:
      - be

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
