services:
  application:
    build:
      context: ./application
      dockerfile: Dockerfile
    image: project_febe_application
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BE_URL=http://be:5000
    networks:
      - app-network
    depends_on:
      - be

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    image: project_febe_be
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FRONTEND_URL=http://fe:3001
    networks:
      - app-network
    depends_on:
      - fe

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    image: project_febe_fe
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - LANG=en_US.UTF-8
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
